### ISSUE TITLE
Undeclared dependencies not caught by the cpp compiler

### ISSUE THREAD

**Issue by lhstrh** [tud-ccc/reactor-cpp#1]
We want to catch any references to undeclared dependencies at compile time, not at run time. Dependencies could be data dependent and remain hidden for a long time if they are only caught at run time.

**Comment by cmnrd** [comment]
I agree that compile time detection of access to undeclared dependencies is a desirable property for Lingua Franca, but I don't think that reactor-cpp is the place to implement this. reactor-cpp is intended as a stand-alone framework that can be used do build reactor programs. Therefore reactor-cpp assumes that the programmer is in full control of the program design. While we can suggest a certain style, enforcing properties of reactors at compile time is difficult as the programmer could find ways around simple restrictions. The only way to actually produce compile errors for any violations of the reactor principles would be by encoding dependencies in the type signature of reactions and to use the C++ type checking for validating them. If we do this to its full extend, it is equivalent to implementing an embedded DSL version of Lingua Franca. This is certainly possible, but I don't think the effort is justified.

I think a better approach is to change code generation in Lingua Franca such that we control the scope of each reaction, so that a reaction only sees the dependencies that where declared in LF. This is similar to what you do in the C target. I am currently thinking about different ways of achieving this and will push some changes to LF.

Does this make sense to you?

**Comment by lhstrh** [comment]
In [reactor-ts](github.com/icyphy/reactor-ts), I'm leveraging TypeScript's scoping rules, visibility modifiers, and type checking mechanisms to ensure that only declared ports can be referenced. This might be overkill, but I think the solution is quite elegant.

That said, if you don't want to go to this extent, following the approach taken in the C generator at least makes mistakes detectable, which I think is the primary concern. The goal is not to guard against actions that intentionally undermine the abstractions that reactors provide but to catch mistakes, which, if they go unchecked, could lead to indeterminate behavior.

**Comment by cmnrd** [comment]
I actually spend yesterday thinking about this issue, but I am still not sure how to address it. It would be possible to build something similar to what you did in reactor-ts using template magic. But there are some caveats to it and it would likely be hard to implement and to maintain. Also, it would not at all prevent active circumvention (by accident due to insufficient knowledge of the reactor semantics or on purpose). I think we should just accept the fact that it is not possible to prevent the programmer from accessing something that was not declared as a dependency before. We should, however, detect this as a runtime error.

In Lingua Franca, we can indeed leverage the code generator to only put in scope what was declared before. I think this is what I will do for now. Simply prepend '__' to any port and action names and then do `auto& port = __port;` in the reaction body.

**Comment by lhstrh** [comment]
That brings the C and C++ runtime on equal footing. Sounds fine to me!
